import type {
  Connector,
  GovernanceMatrix,
  IngestionJob,
  KnowledgeCollection,
  KnowledgeSource,
} from "@/features/knowledge/types";

const now = Date.now();

function hoursAgo(hours: number) {
  return new Date(now - hours * 60 * 60 * 1000).toISOString();
}

export const initialCollections: KnowledgeCollection[] = [
  {
    id: "col-payments-core",
    name: "Payments Core",
    description: "Settlement, reconciliation, and payout runbooks used by operations.",
    owners: ["opslead@opsbrain.ai", "finance.ops@opsbrain.ai"],
    sourcesCount: 0,
    chunksCount: 0,
    lastUpdatedAt: hoursAgo(3),
    defaultAccess: "INTERNAL",
  },
  {
    id: "col-supplier-onboarding",
    name: "Supplier Onboarding",
    description: "Supplier templates, mapping contracts, and connector guides.",
    owners: ["supplier.ops@opsbrain.ai"],
    sourcesCount: 0,
    chunksCount: 0,
    lastUpdatedAt: hoursAgo(12),
    defaultAccess: "INTERNAL",
  },
  {
    id: "col-risk-controls",
    name: "Risk Controls",
    description: "Escalation policies, exposure controls, and risk thresholds.",
    owners: ["risk@opsbrain.ai", "compliance@opsbrain.ai"],
    sourcesCount: 0,
    chunksCount: 0,
    lastUpdatedAt: hoursAgo(7),
    defaultAccess: "RESTRICTED",
  },
  {
    id: "col-marketplace-playbooks",
    name: "Marketplace Playbooks",
    description: "Marketplace-specific exception handling and SLA playbooks.",
    owners: ["marketplace.ops@opsbrain.ai"],
    sourcesCount: 0,
    chunksCount: 0,
    lastUpdatedAt: hoursAgo(26),
    defaultAccess: "INTERNAL",
  },
];

export const initialSources: KnowledgeSource[] = [
  {
    id: "src-supplier-master-q1",
    name: "Supplier Master Mapping Q1.csv",
    type: "UPLOAD",
    collections: ["col-supplier-onboarding", "col-payments-core"],
    status: "INDEXED",
    lastSyncedAt: hoursAgo(1),
    chunksCount: 412,
    access: "INTERNAL",
    owner: "supplier.ops@opsbrain.ai",
    tags: ["supplier", "mapping", "csv"],
    sizeBytes: 2_148_931,
    previewChunks: [
      "SupplierIdentifier normalization: trim spaces, uppercase, remove '-' prefixes for Eneba exports.",
      "OrderNumber fallback policy: use SupplierOrderNumber only when identifier is missing.",
      "Known mismatch edge case: duplicate URL codes from vendor feed can inflate candidate set.",
      "Template schema v3.2 expects columns: supplier_identifier, order_number, card_id, amount, currency.",
      "Validation warning policy: rows with missing brand_name are quarantined for buffer review.",
    ],
  },
  {
    id: "src-eneba-api-runbook",
    name: "Eneba Supplier API Runbook",
    type: "URL",
    collections: ["col-marketplace-playbooks", "col-supplier-onboarding"],
    status: "STALE",
    lastSyncedAt: hoursAgo(44),
    chunksCount: 228,
    access: "INTERNAL",
    owner: "marketplace.ops@opsbrain.ai",
    tags: ["eneba", "api", "runbook"],
    sizeBytes: 664_321,
    url: "https://internal.opsbrain.ai/runbooks/eneba-supplier-api",
    previewChunks: [
      "API throttle behavior: bursts above 120 req/min can return transient 429 with empty error payload.",
      "Retry policy: exponential backoff at 2s, 6s, 12s with request dedupe token.",
      "Contains matching is permitted only on recovery mode and must be logged as low-confidence.",
      "Supplier fetch stage should emit event markers FETCH_START and FETCH_END.",
      "Escalation path: if fetch failure rate exceeds 7%, trigger Jira label supplier-fetch-degraded.",
    ],
  },
  {
    id: "src-risk-threshold-notes",
    name: "Risk Threshold Notes",
    type: "NOTE",
    collections: ["col-risk-controls"],
    status: "INDEXED",
    lastSyncedAt: hoursAgo(6),
    chunksCount: 96,
    access: "RESTRICTED",
    owner: "risk@opsbrain.ai",
    tags: ["risk", "threshold", "policy"],
    sizeBytes: 121_556,
    previewChunks: [
      "Critical exposure threshold: USD 100,000 with auto-escalation to incident channel.",
      "Mismatch warning threshold: 5% sustained across two consecutive runs.",
      "If run remains in IN_PROGRESS > 120 min, classify as potential stuck orchestration state.",
      "Buffer approval requires dual sign-off for runs marked HIGH or CRITICAL severity.",
      "Evidence bundle must include issue samples and event timeline snapshot.",
    ],
  },
  {
    id: "src-slack-incident-feed",
    name: "Slack #supplier-incidents",
    type: "CONNECTOR",
    collections: ["col-marketplace-playbooks"],
    status: "PROCESSING",
    lastSyncedAt: hoursAgo(0.5),
    chunksCount: 178,
    access: "INTERNAL",
    owner: "opslead@opsbrain.ai",
    tags: ["slack", "incidents", "connector"],
    sizeBytes: 482_000,
    connectorId: "conn-slack",
    previewChunks: [
      "Incident 1842: supplier payload missing order numbers for 12-minute window.",
      "Thread summary: manual rerun cleared backlog after supplier endpoint recovered.",
      "Action noted: add validation guard for duplicate code and URL pattern collisions.",
      "Escalation triggered to finance due to exposure crossing warning threshold.",
      "Postmortem item: tighten OR-based matching for partial identifiers.",
    ],
  },
  {
    id: "src-github-reconcile-service",
    name: "GitHub reconcile-service docs",
    type: "CONNECTOR",
    collections: ["col-payments-core"],
    status: "FAILED",
    lastSyncedAt: hoursAgo(9),
    chunksCount: 0,
    access: "INTERNAL",
    owner: "platform@opsbrain.ai",
    tags: ["github", "service", "docs"],
    sizeBytes: 0,
    connectorId: "conn-github",
    errorMessage: "Connector token expired while fetching /docs/reconciliation.md.",
    previewChunks: [
      "No indexed content available due to failed sync.",
      "Reconnect GitHub app and retry ingestion.",
    ],
  },
];

export const initialJobs: IngestionJob[] = [
  {
    id: "JOB-99234",
    sourceId: "src-supplier-master-q1",
    status: "COMPLETED",
    startedAt: hoursAgo(1.3),
    finishedAt: hoursAgo(1),
    durationSec: 1018,
    logs: [
      "[00:00] Upload received and checksum validated.",
      "[00:03] Parsed 17,422 rows.",
      "[00:06] Created 412 semantic chunks.",
      "[00:16] Index commit completed.",
    ],
  },
  {
    id: "JOB-99229",
    sourceId: "src-eneba-api-runbook",
    status: "COMPLETED",
    startedAt: hoursAgo(44.5),
    finishedAt: hoursAgo(44),
    durationSec: 731,
    logs: [
      "[00:00] Web fetch started.",
      "[00:02] Extracted 12 sections.",
      "[00:06] Chunked and embedded 228 records.",
      "[00:12] Index updated.",
    ],
  },
  {
    id: "JOB-99240",
    sourceId: "src-slack-incident-feed",
    status: "RUNNING",
    startedAt: hoursAgo(0.6),
    logs: [
      "[00:00] Connector poll started for #supplier-incidents.",
      "[00:04] Pulled 164 messages.",
      "[00:06] Normalizing threaded replies.",
      "[00:09] Building incremental index batch.",
    ],
  },
  {
    id: "JOB-99236",
    sourceId: "src-github-reconcile-service",
    status: "FAILED",
    startedAt: hoursAgo(9.4),
    finishedAt: hoursAgo(9),
    durationSec: 244,
    error: "GitHub connector unauthorized (401).",
    logs: [
      "[00:00] Connector run started.",
      "[00:01] Fetching repo tree for ops/reconcile-service.",
      "[00:04] Authentication error from GitHub API.",
      "[00:04] Marking job as FAILED.",
    ],
  },
  {
    id: "JOB-99238",
    sourceId: "src-risk-threshold-notes",
    status: "QUEUED",
    startedAt: hoursAgo(0.2),
    logs: [
      "[00:00] Job queued by policy update workflow.",
      "[00:00] Waiting for ingestion worker slot.",
    ],
  },
];

export const initialConnectors: Connector[] = [
  {
    id: "conn-slack",
    name: "Slack",
    status: "CONNECTED",
    lastSyncAt: hoursAgo(0.5),
    description: "Index incident channels and postmortem threads for operational memory.",
  },
  {
    id: "conn-google-drive",
    name: "Google Drive",
    status: "NOT_CONNECTED",
    description: "Sync runbooks and spreadsheet templates from shared drive folders.",
  },
  {
    id: "conn-notion",
    name: "Notion",
    status: "NOT_CONNECTED",
    description: "Ingest team wikis and SOPs from Notion spaces.",
  },
  {
    id: "conn-github",
    name: "GitHub",
    status: "CONNECTED",
    lastSyncAt: hoursAgo(9),
    description: "Ingest documentation and markdown knowledge from selected repositories.",
  },
  {
    id: "conn-confluence",
    name: "Confluence",
    status: "COMING_SOON",
    description: "Enterprise knowledge sync for Atlassian Confluence spaces.",
  },
];

export const initialGovernance: GovernanceMatrix = {
  "col-payments-core": { Admin: true, Ops: true, Finance: true, Viewer: true },
  "col-supplier-onboarding": { Admin: true, Ops: true, Finance: false, Viewer: true },
  "col-risk-controls": { Admin: true, Ops: true, Finance: true, Viewer: false },
  "col-marketplace-playbooks": { Admin: true, Ops: true, Finance: false, Viewer: true },
};
