import type {
  ActionDefinition,
  ActionRun,
  PolicyConfig,
} from "@/features/actions/types";

const now = Date.now();

function hoursAgo(hours: number) {
  return new Date(now - hours * 60 * 60 * 1000).toISOString();
}

export const initialActions: ActionDefinition[] = [
  {
    id: "act-reconcile-payout-mismatch",
    name: "Reconcile Supplier Payout Mismatch",
    description:
      "Detect high-value payout mismatches, generate evidence, and stage corrective supplier reconciliation.",
    type: "automation",
    domain: "reconciliation",
    risk: "high",
    status: "enabled",
    owner: "finance.ops@opsbrain.ai",
    tags: ["reconciliation", "supplier", "evidence"],
    steps: [
      {
        id: "step-1",
        title: "Query mismatch candidates",
        description: "Pull latest mismatch records exceeding configured exposure threshold.",
        kind: "query",
        config: { source: "warehouse.reconciliation_mismatches" },
      },
      {
        id: "step-2",
        title: "Run exposure scoring",
        description: "Compute estimated financial exposure and risk rank.",
        kind: "script",
        config: { script: "scoreMismatchExposure" },
      },
      {
        id: "step-3",
        title: "Create approval task",
        description: "Request Finance approval before applying payout hold and re-run.",
        kind: "approve",
        config: { role: "Finance Manager" },
      },
      {
        id: "step-4",
        title: "Notify incident channel",
        description: "Send summary to #ops-reconciliation-incidents.",
        kind: "notify",
        config: { channel: "ops-reconciliation-incidents" },
      },
    ],
    triggers: [
      { kind: "manual" },
      { kind: "event", eventType: "RUN_MISMATCH_SPIKE" },
    ],
    inputsSchema: [
      { key: "runId", label: "Run ID", type: "text", required: true },
      { key: "supplierId", label: "Supplier ID", type: "text", required: true },
      { key: "maxRecords", label: "Max Records", type: "number", required: false, defaultValue: "500" },
    ],
    safety: {
      requiresApproval: true,
      approverRole: "Finance Manager",
      allowedEnvs: ["staging", "prod"],
      maxScope: 1000,
    },
    createdAt: hoursAgo(280),
    updatedAt: hoursAgo(4),
  },
  {
    id: "act-rerun-xero-sync",
    name: "Re-run Xero Sync for Supplier",
    description:
      "Replays supplier ledger synchronization for a selected date window and verifies posting integrity.",
    type: "runbook",
    domain: "supplier",
    risk: "medium",
    status: "enabled",
    owner: "supplier.ops@opsbrain.ai",
    tags: ["xero", "supplier", "sync"],
    steps: [
      {
        id: "step-1",
        title: "Fetch supplier ledger delta",
        description: "Fetch ledger records from connector API.",
        kind: "api",
        config: { endpoint: "supplier-ledger-delta" },
      },
      {
        id: "step-2",
        title: "Re-run sync stage",
        description: "Invoke sync worker for selected supplier scope.",
        kind: "script",
        config: { worker: "xero-sync" },
      },
      {
        id: "step-3",
        title: "Post completion summary",
        description: "Send execution summary to owner.",
        kind: "notify",
        config: { channel: "supplier-ops" },
      },
    ],
    triggers: [
      { kind: "manual" },
      { kind: "schedule", schedule: "0 */6 * * *" },
    ],
    inputsSchema: [
      { key: "supplierId", label: "Supplier ID", type: "text", required: true },
      { key: "dateFrom", label: "Date From", type: "date", required: true },
      { key: "dateTo", label: "Date To", type: "date", required: true },
    ],
    safety: {
      requiresApproval: false,
      approverRole: "Ops Lead",
      allowedEnvs: ["dev", "staging", "prod"],
      maxScope: 700,
    },
    createdAt: hoursAgo(360),
    updatedAt: hoursAgo(18),
  },
  {
    id: "act-autoclose-duplicates",
    name: "Auto-close duplicate incidents",
    description:
      "Agent action that groups duplicate supplier incidents and closes confirmed duplicates with notes.",
    type: "agent",
    domain: "incident",
    risk: "low",
    status: "enabled",
    owner: "opslead@opsbrain.ai",
    tags: ["incident", "agent", "triage"],
    steps: [
      {
        id: "step-1",
        title: "Cluster incident titles",
        description: "Compute similarity and cluster potential duplicates.",
        kind: "script",
        config: { threshold: 0.86 },
      },
      {
        id: "step-2",
        title: "Close duplicates",
        description: "Close duplicate tickets and link canonical incident.",
        kind: "api",
        config: { target: "jira" },
      },
    ],
    triggers: [{ kind: "schedule", schedule: "*/30 * * * *" }],
    inputsSchema: [
      { key: "projectKey", label: "Project Key", type: "text", required: true, defaultValue: "OPS" },
      { key: "windowHours", label: "Window (hours)", type: "number", required: false, defaultValue: "6" },
    ],
    safety: {
      requiresApproval: false,
      approverRole: "Ops Supervisor",
      allowedEnvs: ["dev", "staging", "prod"],
      maxScope: 300,
    },
    createdAt: hoursAgo(420),
    updatedAt: hoursAgo(2),
  },
  {
    id: "act-governance-access-audit",
    name: "Run Access Policy Drift Audit",
    description:
      "Checks access policy drift across restricted knowledge collections and raises governance alerts.",
    type: "automation",
    domain: "governance",
    risk: "medium",
    status: "draft",
    owner: "compliance@opsbrain.ai",
    tags: ["governance", "audit"],
    steps: [
      {
        id: "step-1",
        title: "Snapshot policy state",
        description: "Read policy matrix and compare baseline.",
        kind: "query",
        config: { source: "policy_matrix" },
      },
      {
        id: "step-2",
        title: "Notify compliance",
        description: "Raise findings with severity tags.",
        kind: "notify",
        config: { channel: "compliance-alerts" },
      },
    ],
    triggers: [{ kind: "manual" }],
    inputsSchema: [
      { key: "collectionId", label: "Collection", type: "text", required: false },
    ],
    safety: {
      requiresApproval: true,
      approverRole: "Compliance Lead",
      allowedEnvs: ["staging", "prod"],
      maxScope: 1200,
    },
    createdAt: hoursAgo(200),
    updatedAt: hoursAgo(26),
  },
];

export const initialRuns: ActionRun[] = [
  {
    id: "ARUN-10082",
    actionId: "act-reconcile-payout-mismatch",
    actionName: "Reconcile Supplier Payout Mismatch",
    triggerKind: "manual",
    environment: "prod",
    startedAt: hoursAgo(0.3),
    status: "running",
    operator: "finance.ops@opsbrain.ai",
    inputs: { runId: "RB-9832", supplierId: "SUP-ENEBA", maxRecords: "500" },
    logs: [
      { t: hoursAgo(0.3), level: "info", message: "Run started from Actions Catalog." },
      { t: hoursAgo(0.29), level: "info", message: "Fetching mismatch candidates for supplier SUP-ENEBA." },
      { t: hoursAgo(0.27), level: "warn", message: "Approval gate pending Finance Manager confirmation." },
    ],
  },
  {
    id: "ARUN-10081",
    actionId: "act-rerun-xero-sync",
    actionName: "Re-run Xero Sync for Supplier",
    triggerKind: "schedule",
    environment: "staging",
    startedAt: hoursAgo(1.1),
    finishedAt: hoursAgo(0.95),
    durationSec: 542,
    status: "success",
    operator: "system@scheduler.opsbrain.ai",
    inputs: { supplierId: "SUP-RUNA", dateFrom: "2026-02-18", dateTo: "2026-02-19" },
    logs: [
      { t: hoursAgo(1.1), level: "info", message: "Scheduled run started." },
      { t: hoursAgo(1.03), level: "info", message: "Fetched 418 ledger records." },
      { t: hoursAgo(0.97), level: "info", message: "Sync worker completed with no posting gaps." },
    ],
    resultSummary: "418 records synchronized. 0 failed postings.",
  },
  {
    id: "ARUN-10080",
    actionId: "act-autoclose-duplicates",
    actionName: "Auto-close duplicate incidents",
    triggerKind: "schedule",
    environment: "prod",
    startedAt: hoursAgo(2.2),
    finishedAt: hoursAgo(2.15),
    durationSec: 173,
    status: "success",
    operator: "system@scheduler.opsbrain.ai",
    inputs: { projectKey: "OPS", windowHours: "6" },
    logs: [
      { t: hoursAgo(2.2), level: "info", message: "Cluster analysis started for open incidents." },
      { t: hoursAgo(2.18), level: "info", message: "Detected 7 duplicate pairs." },
      { t: hoursAgo(2.15), level: "info", message: "Closed duplicates and linked canonical incidents." },
    ],
    resultSummary: "7 duplicate incidents auto-closed.",
  },
  {
    id: "ARUN-10079",
    actionId: "act-rerun-xero-sync",
    actionName: "Re-run Xero Sync for Supplier",
    triggerKind: "manual",
    environment: "prod",
    startedAt: hoursAgo(4.5),
    finishedAt: hoursAgo(4.3),
    durationSec: 725,
    status: "failed",
    operator: "supplier.ops@opsbrain.ai",
    inputs: { supplierId: "SUP-KINGUIN", dateFrom: "2026-02-17", dateTo: "2026-02-18" },
    logs: [
      { t: hoursAgo(4.5), level: "info", message: "Manual run initiated." },
      { t: hoursAgo(4.43), level: "warn", message: "Xero API latency above threshold." },
      { t: hoursAgo(4.31), level: "error", message: "Posting verification mismatch on batch 19." },
    ],
    errorMessage: "Posting verification mismatch detected for batch 19.",
  },
  {
    id: "ARUN-10078",
    actionId: "act-reconcile-payout-mismatch",
    actionName: "Reconcile Supplier Payout Mismatch",
    triggerKind: "event",
    environment: "staging",
    startedAt: hoursAgo(6.4),
    finishedAt: hoursAgo(6.2),
    durationSec: 641,
    status: "success",
    operator: "event-bus@opsbrain.ai",
    inputs: { runId: "RB-9791", supplierId: "SUP-G2A", maxRecords: "300" },
    logs: [
      { t: hoursAgo(6.4), level: "info", message: "Triggered by RUN_MISMATCH_SPIKE." },
      { t: hoursAgo(6.3), level: "info", message: "Generated evidence pack and risk summary." },
      { t: hoursAgo(6.2), level: "info", message: "Approval task created for Finance queue." },
    ],
    resultSummary: "47 records flagged. Approval queued.",
  },
  {
    id: "ARUN-10077",
    actionId: "act-autoclose-duplicates",
    actionName: "Auto-close duplicate incidents",
    triggerKind: "schedule",
    environment: "staging",
    startedAt: hoursAgo(9.8),
    finishedAt: hoursAgo(9.75),
    durationSec: 158,
    status: "cancelled",
    operator: "system@scheduler.opsbrain.ai",
    inputs: { projectKey: "OPS", windowHours: "12" },
    logs: [
      { t: hoursAgo(9.8), level: "info", message: "Run started." },
      { t: hoursAgo(9.77), level: "warn", message: "Cancelled due to maintenance window." },
    ],
    errorMessage: "Cancelled by maintenance freeze policy.",
  },
  {
    id: "ARUN-10076",
    actionId: "act-reconcile-payout-mismatch",
    actionName: "Reconcile Supplier Payout Mismatch",
    triggerKind: "manual",
    environment: "prod",
    startedAt: hoursAgo(15.5),
    finishedAt: hoursAgo(15.2),
    durationSec: 881,
    status: "failed",
    operator: "finance.ops@opsbrain.ai",
    inputs: { runId: "RB-9702", supplierId: "SUP-EPAY", maxRecords: "700" },
    logs: [
      { t: hoursAgo(15.5), level: "info", message: "Run initiated." },
      { t: hoursAgo(15.37), level: "warn", message: "Approval timeout exceeded." },
      { t: hoursAgo(15.2), level: "error", message: "Run aborted after approval timeout." },
    ],
    errorMessage: "Approval timeout exceeded 8 minutes.",
  },
  {
    id: "ARUN-10075",
    actionId: "act-rerun-xero-sync",
    actionName: "Re-run Xero Sync for Supplier",
    triggerKind: "event",
    environment: "dev",
    startedAt: hoursAgo(20.3),
    finishedAt: hoursAgo(20.25),
    durationSec: 138,
    status: "success",
    operator: "event-bus@opsbrain.ai",
    inputs: { supplierId: "SUP-CADOOZ", dateFrom: "2026-02-16", dateTo: "2026-02-16" },
    logs: [
      { t: hoursAgo(20.3), level: "info", message: "Triggered by connector recovery event." },
      { t: hoursAgo(20.26), level: "info", message: "Sync completed for 32 records." },
    ],
    resultSummary: "32 records synchronized successfully.",
  },
];

export const initialPolicyConfig: PolicyConfig = {
  byRisk: {
    low: {
      requiresApproval: false,
      approverRole: "Ops Supervisor",
      maxScope: 1000,
      allowedEnvs: ["dev", "staging", "prod"],
    },
    medium: {
      requiresApproval: true,
      approverRole: "Ops Lead",
      maxScope: 800,
      allowedEnvs: ["staging", "prod"],
    },
    high: {
      requiresApproval: true,
      approverRole: "Finance Manager",
      maxScope: 400,
      allowedEnvs: ["staging", "prod"],
    },
  },
  guardrails: {
    dryRunRequiredHighRisk: true,
    prodRunsRequireFinanceApproval: true,
    max1000RecordsPerRun: true,
    blockIfAnomalyConfidenceLow: true,
  },
};
